/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tuyou_tsd_common_v4l2_V4L2 */

#ifndef _Included_com_tuyou_tsd_common_v4l2_V4L2
#define _Included_com_tuyou_tsd_common_v4l2_V4L2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    openDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_openDevice
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    closeDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_closeDevice
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    queryCapability
 * Signature: (I)Lcom/tuyou/tsd/common/usbcamera/v4l2/V4L2Capability;
 */
JNIEXPORT jobject JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_queryCapability
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    queryCropCapability
 * Signature: (II)Lcom/tuyou/tsd/common/usbcamera/v4l2/V4L2Fract;
 */
JNIEXPORT jobject JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_queryCropCapability
        (JNIEnv *, jobject, jint,jint);

/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    setCrop
 * Signature: (IILandroid/graphics/Rect;)I
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_setCrop
        (JNIEnv *, jobject, jint,jint,jobject);


/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    getCrop
 * Signature: (I)Landroid/graphics/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_getCrop
        (JNIEnv *, jobject, jint);


/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    queryFormat
 * Signature: (II)[Lcom/tuyou/tsd/common/usbcamera/v4l2/V4L2FormatDesc;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_queryFormat
        (JNIEnv *, jobject, jint,jint);

/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    setFormat
 * Signature: (IIIIII)I;
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_setFormat
        (JNIEnv *, jobject, jint,jint,jint,jint,jint,jint);
/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    initmmap
 * Signature: (IIII)I;
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_initmmap
        (JNIEnv *, jobject, jint,jint,jint,jint);


/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    uninitmmap
 * Signature: (I)I;
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_uninitmmap
        (JNIEnv *, jobject, jint);


/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    streamon
 * Signature: (III)I;
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_streamon
        (JNIEnv *, jobject, jint,jint,jint);


/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    streamoff
 * Signature: (II)I;
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_streamoff
        (JNIEnv *, jobject, jint,jint);

/*
 * Class:     com_tuyou_tsd_common_v4l2_V4L2
 * Method:    readFrame
 * Signature: (III[B)I;
 */
JNIEXPORT jint JNICALL Java_com_tuyou_tsd_common_v4l2_V4L2_readFrame
        (JNIEnv *, jobject, jint,jint type,jint memory,jbyteArray);

#ifdef __cplusplus
}
#endif
#endif